output_dir: "output/image_lora"
pretrained_model_path: "[replace with SD1.5 root path]"
unet_subfolder: "unet_webvidlora_v3"

train_data:
  root_path: "[replace RealEstate10K root path]"
  annotation_json: "annotations/train.json"
  sample_size: [256, 384]
  is_image: true

validation_data:
  prompts:
    - "a kitchen with large windows overlooking a lake"
    - "a hallway leading to a laundry room with a washer and dryer"
    - "a bedroom with a bed, chair, and window blinds"
    - "a living room with a couch, piano and tv"
    - "a bathroom with a walk in shower and a bathtub"
    - "a bedroom with an exercise bike and a bed"
    - "a deck with chairs overlooking a wooded area"
    - "the porch of a house is decorated with christmas lights"
    - "a hallway with a staircase and a painting on the wall"
    - "a large brown house with green grass and bushes"
    - "a kitchen with white appliances and wooden cabinets"
    - "a kitchen with wooden cabinets and counter tops"
    - "a bedroom with a large bed and a chandelier"
    - "a kitchen and dining room with hardwood floors"
    - "a hallway leading to a bedroom and bathroom"
    - "a dining room with a chandelier hanging from the ceiling"
  num_inference_steps: 50
  guidance_scale: 8.

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "scaled_linear"
  steps_offset: 1
  clip_sample: false

do_sanity_check:      true
max_train_epoch:      -1
max_train_steps:      10000
validation_steps:       2000
validation_steps_tuple: [2,]

learning_rate:    1.e-4

lora_rank: 2

num_workers: 8
train_batch_size: 32

checkpointing_epochs: -1
checkpointing_steps:  2000

mixed_precision_training: true
enable_xformers_memory_efficient_attention: false

global_seed: 42
logger_interval: 10
